title           : "Catetinho: trajetórias na apropriação de um monumento incomum"
author:
  name          : "Marina Martins Mennucci e Pedro Paulo Palazzo"
  email         : "labeurbe@unb.br"
description: >-
  Problemas em torno da memória, conservação e musealização do Catetinho,
  a primeira residência e local de trabalho da Novacap na construção de
  Brasília, obra de Oscar Niemeyer construída em 1956 e tombada em 1959.
baseurl         : "/catetinho"
url             : "https://dmcpatrimonio.github.io" 
lang            : pt

# Content settings {{{1
header_pages:
  6icch-mencfp.md
  ar-catetinho.md

collections:
  biblio:

# defaults:

# Template settings {{{1
remote_theme    : p3palazzo/minima-scholar
minima:
  date_format   : "%e %B %Y"
  social_links:
    github      : https://github.com/dmcpatrimonio/catetinho

# Build settings {{{1
source          : docs/
markdown        : kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - kramdown
    # The following plugins are always used by GH-Pages
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
permalink         : pretty
kramdown:
  auto_ids        : true
  header_offset   : 1
  transliterated_header_ids: true
relative_links:
  enabled         : true
  collections     : true
readme_index:
  enabled         : true
  remove_originals: true
  with_frontmatter: true

# vim: set foldmethod=marker :
