title           : "Catetinho: trajetórias na apropriação de um monumento incomum"
author:
  name          : "Marina Martins Mennucci e Pedro Paulo Palazzo"
  email         : "labeurbe@unb.br"
description: >-
  Problemas em torno da memória, conservação e musealização do Catetinho,
  a primeira residência e local de trabalho da Novacap na construção de
  Brasília, obra de Oscar Niemeyer construída em 1956 e tombada em 1959.
baseurl         : "/catetinho"
url             : "https://dmcpatrimonio.github.io" 
lang            : pt

# Content settings {{{1
header_pages:
  6icch-mencfp.md

collections:
  biblio:

# defaults:

# Template settings {{{1
theme           : minima
minima:
  date_format   : "%e %b %y"
  social_links:
    github      : https://github.com/dmcpatrimonio/catetinho

# Build settings {{{1
source          : /docs
markdown        : kramdown
kramdown:
  auto_ids      : true
  header_offset : 1
  transliterated_header_ids: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - kramdown
    # The following plugins are always used by GH-Pages
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-titles-from-headings

readme_index:
  enabled         : true
  remove_originals: true
  with_frontmatter: true

google_analytics:
exclude:

# vim: set foldmethod=marker :
